### ISSUE TITLE
Still get refs/heads prefix in outputs

### ISSUE THREAD

**Issue by huygn** [tj-actions/branch-names#4]
### Description

I'm trying to get branch name from a direct branch push.

### What I Did

Used `${{ steps.branch_name.outputs.ref_branch }}` but still receive `refs/heads/<branch>` prefix in outputs.

![image](https://user-images.githubusercontent.com/10569203/103070178-8bd08480-45f3-11eb-9429-3a52e9f922c7.png)

**Comment by jackton1** [comment]
This should be resolved in the next release.

Thanks @huygn
