### ISSUE TITLE
[BUG] No current_branch on release.

### ISSUE THREAD

**Issue by almed4** [tj-actions/branch-names#50]
**Describe the bug**
Running a github action caused by a release cut from develop. When using branch-names, current_branch is null during the workflow.

**To Reproduce**
1. Create workflow with tj-actions/branch-names@v4.1
2. Design workflow to trigger on release.
3. Cut release from branch w/ workflow
4. current_branch is null

**Expected behavior**
current_branch shows branch name of branch release is cut from

**Desktop (please complete the following information):**
 - OS: github action ubuntu-latest
 - Version v4.1

**Comment by jackton1** [comment]
This should be fixed now using the latest patch `v4.2` or `v4`. Thanks @almed4

**Comment by almed4** [comment]
Thanks @jackton1! Incredible turnaround.
