### ISSUE TITLE
🙏🙏🙏🙏🙏 Thanks for making this 👏👏👏👏

### ISSUE THREAD

**Issue by brookemitchell** [tj-actions/branch-names#87]
### Is your feature request related to a problem? Please describe.

No more (well you well know it gets much more complicated)
` echo "BRANCH=$(echo ${${{ github.ref || github.head_ref  }}#refs/<type>/} || )">>"$GITHUB_ENV"` for us!

ugh that was annoying!

Seriously, thanks!

### Describe the solution you'd like?

Keep it up! Closing now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@brookemitchell Your Welcome, don’t forget to support the project with a ⭐. 

Thanks
